name:                timeout-sesstype
version:             0.1.0.0
github:              "matsubara0507/timeout-sesstype.hs"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/matsubara0507/timeout-sesstype#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- extensible
- lens
- text

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - megaparsec

executables:
  timeout-sesstype-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeout-sesstype

tests:
  timeout-sesstype-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeout-sesstype
